"""Deterministic global typed candidate discovery and Transfer-12 utilities.

Candidate identity is derived only from canonical concept rows, structural
Toronto Notes headings, or already-reviewed identities.  No chunk prose is
read and no medical identity is generated by this module.
"""

from __future__ import annotations

import hashlib
import json
import re
import sqlite3
from collections import defaultdict
from typing import Any, Iterable, Mapping, Sequence

from .contrast_supply import _is_ambiguous_label, _is_extraction_artifact, _is_generic_label
from .option_set_admissibility import RESPONSE_CLASS_AXES


V3_CANDIDATE_BUDGET = 10
DISCOVERY_V3_VERSION = "GLOBAL_TYPED_DISCOVERY_V3_1"
DISCIPLINE_ORDER = ("MED", "PED", "OBGYN", "SURG", "PSY", "PHELO")


def canonical_content_sha256(value: Mapping[str, Any]) -> str:
    payload = {key: item for key, item in value.items() if key != "content_sha256"}
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(encoded.encode()).hexdigest()


def select_transfer_12(
    evidence_rows: Sequence[Mapping[str, Any]],
    feature_maps: Sequence[Mapping[str, Any]],
    *,
    excluded_ids: set[str],
) -> list[dict[str, Any]]:
    """Select the first two eligible rows per discipline without outcome data.

    Input is deliberately limited to evidence/readiness and feature-presence
    records. Candidate, discovery, cache, and contrast fields are neither
    accepted nor consulted.
    """
    feature_ready = {row["development_id"] for row in feature_maps}
    by_discipline: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for row in evidence_rows:
        development_id = row["development_id"]
        if development_id in excluded_ids or development_id not in feature_ready:
            continue
        if row.get("audit_verdict") != "ALIGNED_COMPLETE":
            continue
        by_discipline[row["discipline"]].append(row)

    result: list[dict[str, Any]] = []
    for discipline in DISCIPLINE_ORDER:
        eligible = sorted(by_discipline[discipline], key=lambda row: row["development_id"])
        if len(eligible) < 2:
            raise ValueError(f"{discipline} has fewer than two evidence+feature-ready rows")
        for row in eligible[:2]:
            result.append({
                key: row[key]
                for key in (
                    "development_id", "discipline", "study_unit_id",
                    "learner_decision_id", "learner_decision",
                )
                if key in row
            })
    return result


def _canonical_label(label: str) -> str:
    return " ".join(label.strip().split())


def _safe_identity(label: str | None) -> bool:
    if not label:
        return False
    return not (
        _is_generic_label(label)
        or _is_ambiguous_label(label)
        or _is_extraction_artifact(label)
        or len(label.split()) > 14
        or bool(re.search(r"[.!?]$", label.strip()))
    )


def _safe_reviewed_identity(label: str | None) -> bool:
    """Reviewed identities may use slash-separated synonymous formulations."""
    if not label:
        return False
    return not (_is_generic_label(label) or len(label.split()) > 24)


def _has_reviewed_identity_provenance(row: Mapping[str, Any]) -> bool:
    return any(
        item.get("source") in {
            "INDEPENDENTLY_APPROVED_SEED",
            "INDEPENDENTLY_APPROVED_AOM_CONTROL",
            "REUSABLE_CONTRAST_CACHE_V1",
            "independent-review",
            "reviewed",
        }
        for item in row.get("provenance", [])
    )


def _merge_row(target: dict[str, Any], source: Mapping[str, Any]) -> None:
    for key in ("aliases", "source_ids", "chapters", "study_unit_ids",
                "section_paths", "semantic_families", "response_classes",
                "decision_granularities", "provenance"):
        values = source.get(key) or []
        existing = target.setdefault(key, [])
        for value in values:
            if value not in existing:
                existing.append(value)
    for key in ("parent_candidate_id", "subtype_of"):
        if source.get(key):
            target[key] = source[key]


def build_global_candidate_catalogue(
    connection: sqlite3.Connection,
    *,
    reviewed_identities: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    """Build a canonical candidate-identity catalogue from metadata only."""
    rows: dict[str, dict[str, Any]] = {}
    query = """
      SELECT c.concept_id, c.concept_type, c.preferred_label, c.vocabulary_source,
             c.provenance, m.matched_surface_form, m.chunk_id, ch.chapter_code,
             ch.tn_node_id, ch.section_path, ch.subheading, su.study_unit_id
      FROM concepts c
      LEFT JOIN concept_mentions m ON m.concept_id = c.concept_id
      LEFT JOIN chunks ch ON ch.chunk_id = m.chunk_id
      LEFT JOIN chunk_study_units su ON su.chunk_id = ch.chunk_id
      ORDER BY c.concept_id, m.chunk_id, m.matched_surface_form, su.study_unit_id
    """
    for record in connection.execute(query):
        (concept_id, concept_type, label, vocabulary_source, concept_provenance,
         surface, chunk_id, chapter, tn_node_id, section_path, subheading,
         study_unit_id) = record
        if not _safe_identity(label):
            continue
        row = rows.setdefault(concept_id, {
            "canonical_candidate_id": concept_id,
            "normalized_label": _canonical_label(label),
            "aliases": [],
            "source_ids": [],
            "chapters": [],
            "study_unit_ids": [],
            "section_paths": [],
            "graph_identity": {"concept_type": concept_type, "vocabulary_source": vocabulary_source},
            "semantic_families": [concept_type.lower()] if concept_type else [],
            "response_classes": [],
            "decision_granularities": [],
            "provenance": [],
        })
        if surface and _safe_identity(surface) and _canonical_label(surface).casefold() != label.casefold():
            if _canonical_label(surface) not in row["aliases"]:
                row["aliases"].append(_canonical_label(surface))
        if chunk_id and chunk_id not in row["source_ids"]:
            row["source_ids"].append(chunk_id)
            row["provenance"].append({
                "source": "CANONICAL_CONCEPT_MENTION",
                "chunk_id": chunk_id,
                "tn_node_id": tn_node_id,
                "subheading": subheading,
                "section_path": section_path,
                "concept_provenance": concept_provenance,
            })
        if chapter and chapter not in row["chapters"]:
            row["chapters"].append(chapter)
        if study_unit_id and study_unit_id not in row["study_unit_ids"]:
            row["study_unit_ids"].append(study_unit_id)
        if section_path and section_path not in row["section_paths"]:
            row["section_paths"].append(section_path)

    for reviewed in reviewed_identities:
        concept_id = reviewed.get("canonical_candidate_id") or reviewed.get("candidate_id")
        label = reviewed.get("normalized_label") or reviewed.get("candidate_label")
        if not concept_id or not _safe_reviewed_identity(label):
            continue
        target = rows.setdefault(concept_id, {
            "canonical_candidate_id": concept_id,
            "normalized_label": _canonical_label(label),
            "aliases": [], "source_ids": [], "chapters": [], "study_unit_ids": [],
            "section_paths": [], "graph_identity": reviewed.get("graph_identity"),
            "semantic_families": [], "response_classes": [],
            "decision_granularities": [], "provenance": [],
        })
        _merge_row(target, reviewed)

    for row in rows.values():
        for key in ("aliases", "source_ids", "chapters", "study_unit_ids",
                    "section_paths", "semantic_families", "response_classes",
                    "decision_granularities"):
            row[key] = sorted(row[key], key=lambda value: str(value).casefold())
        row["provenance"] = sorted(row["provenance"], key=lambda value: json.dumps(value, sort_keys=True))
    return [rows[key] for key in sorted(rows)]


def discover_global_typed_candidates(
    catalogue: Sequence[Mapping[str, Any]],
    *,
    opportunity: Mapping[str, Any],
) -> list[dict[str, Any]]:
    """Filter then rank global canonical concepts; locality is only a bonus."""
    response_class = opportunity["demanded_response_class"]
    granularity = opportunity["decision_granularity"]
    key_aliases = {str(value).casefold() for value in opportunity.get("key_aliases", [])}
    wanted_families = set(opportunity.get("semantic_families", []))
    ranked: list[tuple[tuple[int, int, int, str], dict[str, Any]]] = []
    for original in catalogue:
        label = str(original["normalized_label"])
        aliases = {label.casefold(), *(str(value).casefold() for value in original.get("aliases", []))}
        identity_safe = (
            _safe_reviewed_identity(label)
            if _has_reviewed_identity_provenance(original)
            else _safe_identity(label)
        )
        if aliases & key_aliases or not identity_safe:
            continue
        candidate_classes = set(original.get("response_classes", []))
        compatible_classes = {response_class}
        for definition in RESPONSE_CLASS_AXES.values():
            if response_class == definition["generic_token"]:
                compatible_classes.update(definition["tokens"])
                break
        if not (candidate_classes & compatible_classes):
            continue
        granularities = set(original.get("decision_granularities", []))
        if granularities and granularity not in granularities:
            continue
        same_unit = opportunity.get("study_unit_id") in set(original.get("study_unit_ids", []))
        same_chapter = opportunity.get("chapter_code") in set(original.get("chapters", []))
        family_match = bool(wanted_families & set(original.get("semantic_families", [])))
        row = dict(original)
        row["cross_study_unit"] = not same_unit
        row["cross_chapter"] = not same_chapter
        row["ranking_signals"] = {
            "response_class_match": True,
            "granularity_match": not granularities or granularity in granularities,
            "semantic_family_match": family_match,
            "same_study_unit": same_unit,
            "same_chapter": same_chapter,
        }
        score = (0 if family_match else 1, 0 if same_unit else 1, 0 if same_chapter else 1, concept_sort_key(row))
        ranked.append((score, row))
    return [row for _, row in sorted(ranked, key=lambda item: item[0])[:V3_CANDIDATE_BUDGET]]


def concept_sort_key(row: Mapping[str, Any]) -> str:
    return str(row["canonical_candidate_id"])


def build_append_only_cache(
    parent: Mapping[str, Any],
    additions: Sequence[Mapping[str, Any]],
    *,
    version: str,
) -> dict[str, Any]:
    """Create an explicit child cache without mutating or shadowing the parent."""
    parent_hash = parent.get("content_sha256")
    if not isinstance(parent_hash, str) or len(parent_hash) != 64:
        raise ValueError("an explicit parent content hash is required")
    entries = {key: dict(value) for key, value in parent.get("entries", {}).items()}
    new_keys: list[str] = []
    for addition in additions:
        key = addition.get("cache_key")
        if not key:
            raise ValueError("a cache addition needs cache_key")
        if key in entries:
            raise ValueError(f"append-only cache may not overwrite parent key {key}")
        if addition.get("review_status") != "APPROVED" or not addition.get("anchor_id"):
            raise ValueError(f"cache addition {key} needs an independently approved anchor")
        row = {field: value for field, value in addition.items() if field != "cache_key"}
        entries[key] = row
        new_keys.append(key)
    value = {
        "schema_version": f"REUSABLE_CONTRAST_CACHE_{version}",
        "parent_content_sha256": parent_hash,
        "approved_entry_count": len(entries),
        "new_entry_count": len(new_keys),
        "new_entry_keys": sorted(new_keys),
        "entries": entries,
    }
    value["content_sha256"] = canonical_content_sha256(value)
    return value
