"""Authored, evidence-gated specification for the fresh QGEN holdout.

This file is deliberately declarative.  The roster and feature maps were
authored without consulting seed retrieval.  ``build_fresh_holdout_24.py``
validates the declarations and freezes their hashes.
"""

from __future__ import annotations


def _row(
    discipline, unit, title, mcc, decision, statement, response, granularity,
    archetype, priority, difficulty, evidence, features, *, context=None,
):
    return {
        "opportunity_id": f"QH24-{discipline}-{unit.replace('SU-', '').replace('-', '')}",
        "discipline": discipline,
        "study_unit_id": unit,
        "allocation_address_id": unit,
        "study_unit": title,
        "mcc_objective_ids": mcc,
        "learner_decision_id": f"LD-H24-{unit.replace('SU-', '').replace('-', '')}",
        "learner_decision": statement,
        "decision_contract": decision,
        "response_class": response,
        "decision_granularity": granularity,
        "item_archetype": archetype,
        "priority": priority,
        "difficulty_intent": difficulty,
        "evidence_refs": evidence,
        "evidence_readiness": "ALIGNED_COMPLETE",
        "context": context or {},
        "features": [
            {
                "feature_id": f"SF-H24-{unit.replace('SU-', '').replace('-', '')}-{i:02d}",
                "state": state,
                "clinical_role": role,
                "description": text,
            }
            for i, (state, role, text) in enumerate(features, 1)
        ],
    }


HOLDOUT_SPECS = [
    _row("MED", "SU-A-25", "Local Anesthetic Systemic Toxicity (LAST)", ["13", "92"],
         "DIAGNOSIS", "Recognize early local-anesthetic systemic toxicity after local-anesthetic exposure.",
         "PLAUSIBLE_DIAGNOSTIC_ENTITY", "DIAGNOSIS", "DIAGNOSIS_SET", "CORE", "MEDIUM",
         ["SRC-MED-006-REC-01"], [("PRESENT", "TEMPORAL_ANCHOR", "Symptoms begin soon after local-anesthetic administration."), ("PRESENT", "POSITIVE_SUPPORT", "Metallic taste and circumoral numbness."), ("PRESENT", "POSITIVE_SUPPORT", "New dizziness and disorientation.")]),
    _row("MED", "SU-A-33", "Malignant Hyperthermia", ["107-1"],
         "EMERGENCY_STABILIZATION", "Give dantrolene promptly for a suspected malignant-hyperthermia crisis.",
         "PHARMACOLOGIC_ACTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "HARD",
         ["SRC-MED-009-REC-01"], [("PRESENT", "TEMPORAL_ANCHOR", "Hypermetabolic changes develop during general anesthesia."), ("PRESENT", "POSITIVE_SUPPORT", "Rapid unexplained rise in end-tidal carbon dioxide."), ("PRESENT", "RISK_FEATURE", "Rigidity and hyperthermia are evolving.")], context={"risk_relevant": True, "risk_context": "active anesthetic crisis"}),
    _row("MED", "SU-C-23", "Congestive Heart Failure", ["27", "29-1"],
         "DIAGNOSIS", "Diagnose heart failure from a compatible syndrome plus objective cardiac abnormality.",
         "PLAUSIBLE_DIAGNOSTIC_ENTITY", "DIAGNOSIS", "DIAGNOSIS_SET", "CORE", "MEDIUM",
         ["SRC-MED-019-REC-01"], [("PRESENT", "SHARED_PLAUSIBILITY_FEATURE", "Progressive exertional dyspnea and orthopnea."), ("PRESENT", "POSITIVE_SUPPORT", "Elevated jugular venous pressure and bilateral edema."), ("PRESENT", "KEY_DISCRIMINATOR", "Echocardiography shows impaired ventricular function.")]),
    _row("MED", "SU-C-29", "Valvular Heart Disease", ["62"],
         "NEXT_INVESTIGATION", "Order echocardiography to characterize suspected valvular heart disease.",
         "STRUCTURAL", "DIAGNOSTIC_TEST", "INVESTIGATION_SET", "CORE", "EASY",
         ["SRC-MED-023-REC-01"], [("PRESENT", "SHARED_PLAUSIBILITY_FEATURE", "New pathologic systolic murmur."), ("PRESENT", "POSITIVE_SUPPORT", "Exertional symptoms compatible with valve disease."), ("ABSENT", "SAFETY_BOUNDARY", "No hemodynamic instability requiring immediate stabilization.")]),

    _row("PED", "SU-P-003", "Routine Immunization", ["74-2"],
         "SCREENING_PREVENTION", "Proceed with routine vaccination when a child has only a mild acute illness.",
         "PATIENT_INSTRUCTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "EASY",
         ["H24-PED-IMMUNIZATION-01"], [("PRESENT", "AGE_CONTEXT", "Child is due for routine immunization."), ("PRESENT", "SAFETY_BOUNDARY", "Illness is mild."), ("ABSENT", "SAFETY_BOUNDARY", "No anaphylaxis to the vaccine or component.")], context={"age": "18 months"}),
    _row("PED", "SU-P-019", "Sudden Infant Death Syndrome (SIDS)", ["104", "104-1"],
         "SCREENING_PREVENTION", "Recommend supine sleep on a firm, flat, separate infant sleep surface.",
         "PATIENT_INSTRUCTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "EASY",
         ["H24-PED-SAFE-SLEEP-01"], [("PRESENT", "AGE_CONTEXT", "Healthy young infant."), ("PRESENT", "DECISION_TRIGGER", "Caregiver requests sleep-safety advice."), ("ABSENT", "SAFETY_BOUNDARY", "No medical indication for an alternative sleep position.")], context={"age": "2 months"}),
    _row("PED", "SU-P-055", "Approach to the Infant/Child with Dehydration", ["22-3"],
         "INITIAL_MANAGEMENT", "Use oral rehydration solution for mild pediatric dehydration.",
         "NEXT_ACTION_FOR_CURRENT_CARE", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["H24-PED-DEHYDRATION-01"], [("PRESENT", "AGE_CONTEXT", "Young child with acute diarrhea."), ("PRESENT", "SEVERITY_FEATURE", "Clinical findings indicate mild dehydration."), ("ABSENT", "SAFETY_BOUNDARY", "No shock or inability to drink.")], context={"age": "3 years"}),
    _row("PED", "SU-P-071", "Constipation (Pediatric)", ["16-2"],
         "MEDICATION_SELECTION", "Select polyethylene glycol 3350 for maintenance treatment of functional constipation.",
         "PHARMACOLOGIC_ACTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["H24-PED-CONSTIPATION-01"], [("PRESENT", "AGE_CONTEXT", "School-aged child."), ("PRESENT", "POSITIVE_SUPPORT", "Chronic hard painful stools consistent with functional constipation."), ("ABSENT", "SAFETY_BOUNDARY", "No red flags for an organic cause.")], context={"age": "7 years"}),

    _row("OBGYN", "SU-GY-06", "Abnormal Uterine Bleeding", ["112"],
         "INITIAL_MANAGEMENT", "Offer tranexamic acid as a non-hormonal option for stable heavy menstrual bleeding when contraception is not desired.",
         "PHARMACOLOGIC_ACTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["SRC-OBGYN-080-REC-01", "SRC-OBGYN-080-REC-02"], [("PRESENT", "SHARED_PLAUSIBILITY_FEATURE", "Stable heavy cyclic bleeding."), ("PRESENT", "PREFERENCE_FEATURE", "Patient wants a non-hormonal option and does not need contraception."), ("ABSENT", "SAFETY_BOUNDARY", "Pregnancy and hemodynamic instability are excluded.")]),
    _row("OBGYN", "SU-GY-40", "Fibroids (Uterine Leiomyoma)", ["112", "2"],
         "INITIAL_MANAGEMENT", "Use observation rather than active treatment for an asymptomatic fibroid.",
         "NO_ACTIVE_TREATMENT", "MANAGEMENT_STRATEGY", "MANAGEMENT_STRATEGY_SET", "IMPORTANT", "EASY",
         ["SRC-OBGYN-082-REC-01"], [("PRESENT", "KEY_DISCRIMINATOR", "Fibroid is incidentally identified and asymptomatic."), ("ABSENT", "SAFETY_BOUNDARY", "No bleeding, bulk symptoms, or fertility concern."), ("PRESENT", "STABILITY_FEATURE", "Examination and hemoglobin are reassuring.")]),
    _row("OBGYN", "SU-OB-11", "Counselling of the Pregnant Patient", ["80-1"],
         "SCREENING_PREVENTION", "Offer Tdap during every pregnancy, ideally at 27–32 weeks.",
         "PATIENT_INSTRUCTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["SRC-OBGYN-074-REC-01", "SRC-OBGYN-074-REC-02"], [("PRESENT", "GESTATIONAL_CONTEXT", "Pregnancy is at 28 weeks."), ("PRESENT", "DECISION_TRIGGER", "Routine antenatal vaccine review."), ("ABSENT", "SAFETY_BOUNDARY", "No vaccine-specific contraindication.")], context={"pregnancy_postpartum_relevant": True, "gestational_age_or_postpartum_day": "28 weeks gestation"}),
    _row("OBGYN", "SU-OB-56", "Postpartum Care", ["80-2"],
         "INITIAL_MANAGEMENT", "Arrange maternal follow-up within 48 hours after postpartum discharge.",
         "NEXT_ACTION_FOR_CURRENT_CARE", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["SRC-OBGYN-073-REC-01"], [("PRESENT", "POSTPARTUM_CONTEXT", "Uncomplicated early postpartum discharge."), ("PRESENT", "DECISION_TRIGGER", "Discharge and follow-up planning is being completed."), ("ABSENT", "SAFETY_BOUNDARY", "No acute maternal or infant issue requiring immediate assessment.")], context={"pregnancy_postpartum_relevant": True, "gestational_age_or_postpartum_day": "postpartum day 1"}),

    _row("SURG", "SU-GS-73", "Groin Hernias", ["2-4"],
         "INITIAL_MANAGEMENT", "Offer watchful waiting to a carefully selected patient with an asymptomatic or minimally symptomatic inguinal hernia.",
         "NO_ACTIVE_TREATMENT", "MANAGEMENT_STRATEGY", "MANAGEMENT_STRATEGY_SET", "CORE", "MEDIUM",
         ["H24-SURG-HERNIA-01"], [("PRESENT", "POSITIVE_SUPPORT", "Reducible clinically evident inguinal hernia."), ("PRESENT", "KEY_DISCRIMINATOR", "No or minimal symptoms."), ("ABSENT", "SAFETY_BOUNDARY", "No incarceration, strangulation, or obstructive symptoms.")]),
    _row("SURG", "SU-OR-57", "Ankle Ligamentous Injuries", ["109-3"],
         "NEXT_INVESTIGATION", "Do not order ankle radiographs when the Ottawa ankle rules are negative.",
         "CLINICAL_OBSERVATION", "DIAGNOSTIC_TEST", "INVESTIGATION_SET", "CORE", "MEDIUM",
         ["H24-SURG-ANKLE-01"], [("PRESENT", "POSITIVE_SUPPORT", "Inversion injury with lateral ankle pain."), ("ABSENT", "KEY_DISCRIMINATOR", "No posterior malleolar-edge or tip tenderness."), ("PRESENT", "KEY_DISCRIMINATOR", "Able to bear weight for four steps.")]),
    _row("SURG", "SU-U-13", "Testicular Tumour Recognition", ["90"],
         "NEXT_INVESTIGATION", "Order scrotal ultrasonography for a suspicious painless intratesticular mass.",
         "STRUCTURAL", "DIAGNOSTIC_TEST", "INVESTIGATION_SET", "IMPORTANT", "MEDIUM",
         ["H24-SURG-TESTIS-01"], [("PRESENT", "POSITIVE_SUPPORT", "New painless firm intratesticular mass."), ("ABSENT", "SAFETY_BOUNDARY", "No acute torsion syndrome."), ("PRESENT", "DECISION_TRIGGER", "Initial diagnostic evaluation is required.")]),
    _row("SURG", "SU-U-22", "Cryptorchidism and Ectopic Testes", ["36-2"],
         "INITIAL_MANAGEMENT", "Refer persistent cryptorchidism by six months corrected age without routine imaging.",
         "NEXT_ACTION_FOR_CURRENT_CARE", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "IMPORTANT", "MEDIUM",
         ["H24-SURG-CRYPTORCHIDISM-01"], [("PRESENT", "AGE_CONTEXT", "Infant is six months corrected age."), ("PRESENT", "KEY_DISCRIMINATOR", "Testis remains nonpalpable in the scrotum."), ("ABSENT", "SAFETY_BOUNDARY", "No acute scrotal emergency.")]),

    _row("PSY", "SU-PS-04", "Suicide Risk Assessment and Management", ["59-1"],
         "EMERGENCY_STABILIZATION", "Secure continuous observation and arrange emergency psychiatric assessment for imminent suicide risk.",
         "SECURES_IMMEDIATE_SAFETY", "DISPOSITION", "DISPOSITION_SET", "CORE", "HARD",
         ["H24-PSY-SUICIDE-01"], [("PRESENT", "RISK_FEATURE", "Current intent, plan, and access to lethal means."), ("PRESENT", "RISK_FEATURE", "Cannot commit to immediate safety."), ("ABSENT", "SAFETY_BOUNDARY", "No reliable safe outpatient supervision.")], context={"risk_relevant": True, "risk_context": "imminent suicide risk"}),
    _row("PSY", "SU-PS-14", "Bipolar Disorders", ["59-1"],
         "MEDICATION_SELECTION", "Select a guideline-supported first-line antimanic agent for acute mania.",
         "PHARMACOLOGIC_ACTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["H24-PSY-MANIA-01"], [("PRESENT", "POSITIVE_SUPPORT", "Acute mania without depressive features."), ("PRESENT", "SEVERITY_FEATURE", "Marked impairment requires active pharmacotherapy."), ("ABSENT", "SAFETY_BOUNDARY", "No stated contraindication to the selected first-line agent.")]),
    _row("PSY", "SU-PS-25", "Delirium", ["58-2"],
         "INITIAL_MANAGEMENT", "Identify and correct the reversible cause while providing supportive delirium care.",
         "NEXT_ACTION_FOR_CURRENT_CARE", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["H24-PSY-DELIRIUM-01"], [("PRESENT", "POSITIVE_SUPPORT", "Acute fluctuating inattention and altered awareness."), ("PRESENT", "DECISION_TRIGGER", "A potential reversible medical precipitant is present."), ("ABSENT", "SAFETY_BOUNDARY", "No immediate violent behaviour requiring emergency sedation.")]),
    _row("PSY", "SU-PS-30", "Opioid Use Disorder", ["103", "103-1"],
         "MEDICATION_SELECTION", "Offer buprenorphine/naloxone as first-line opioid agonist treatment when appropriate.",
         "PHARMACOLOGIC_ACTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["H24-PSY-OUD-01"], [("PRESENT", "POSITIVE_SUPPORT", "Moderate-to-severe opioid use disorder."), ("PRESENT", "DECISION_TRIGGER", "Patient requests evidence-based maintenance treatment."), ("ABSENT", "SAFETY_BOUNDARY", "No clinical factor making buprenorphine initiation inappropriate.")]),

    _row("PHELO", "SU-ELOM-11", "Truth-Telling", ["121-2"],
         "COMMUNICATION", "Explore the patient's understanding before giving serious-illness information in small plain-language portions and checking understanding.",
         "COMMUNICATION_ACTION", "SINGLE_NEXT_ACTION", "NEXT_ACTION_SET", "CORE", "MEDIUM",
         ["REC-SRC-PHELO-002-01"], [("PRESENT", "DECISION_TRIGGER", "A serious diagnosis must be discussed."), ("PRESENT", "PREFERENCE_FEATURE", "Patient wants to participate in decisions."), ("ABSENT", "SAFETY_BOUNDARY", "No request to withhold information from the patient.")]),
    _row("PHELO", "SU-PH-09", "Measures of Disease Occurrence", ["78-2"],
         "INTERPRETATION", "Interpret a reported population rate only with its defined population and denominator.",
         "EXPLANATION_OF_OBSERVED_PHENOMENON", "EPIDEMIOLOGIC_EXPLANATION", "STATISTICAL_INTERPRETATION_SET", "CORE", "MEDIUM",
         ["REC-SRC-PHELO-013-01"], [("PRESENT", "DECISION_TRIGGER", "Two crude event counts are being compared."), ("ABSENT", "KEY_DISCRIMINATOR", "Population denominators are not supplied."), ("PRESENT", "SAFETY_BOUNDARY", "The requested conclusion concerns a rate, not a count.")]),
    _row("PHELO", "SU-PH-13", "Interpreting Diagnostic Test Results", ["78-2"],
         "INTERPRETATION", "Explain a lower positive predictive value by the lower prevalence in the tested population when sensitivity and specificity are unchanged.",
         "EXPLANATION_OF_OBSERVED_PHENOMENON", "EPIDEMIOLOGIC_EXPLANATION", "STATISTICAL_INTERPRETATION_SET", "CORE", "HARD",
         ["H24-PHELO-DIAGNOSTIC-TEST-01"], [("PRESENT", "KEY_DISCRIMINATOR", "Sensitivity and specificity are identical in both settings."), ("PRESENT", "KEY_DISCRIMINATOR", "Disease prevalence is lower in primary care."), ("PRESENT", "DECISION_TRIGGER", "Positive predictive value is lower in primary care.")]),
    _row("PHELO", "SU-PH-14", "Effectiveness of Interventions and Measures of Effect", ["78-2", "78-4"],
         "INTERPRETATION", "Explain why identical relative risk reductions can produce different absolute benefits when baseline risks differ.",
         "EXPLANATION_OF_OBSERVED_PHENOMENON", "EPIDEMIOLOGIC_EXPLANATION", "STATISTICAL_INTERPRETATION_SET", "CORE", "HARD",
         ["H24-PHELO-NNT-01"], [("PRESENT", "KEY_DISCRIMINATOR", "Relative risk reduction is identical in two populations."), ("PRESENT", "KEY_DISCRIMINATOR", "Baseline event risks differ."), ("PRESENT", "DECISION_TRIGGER", "Absolute risk reductions and NNTs differ.")]),
]
