"""Bounded semantic inputs for the generalized pre-holdout readiness wave.

These rows deliberately describe one narrow learner decision per development
unit.  They are not question stems and contain no distractor or seed material.
"""

EXISTING_READY = {
    "RDY-MED-01": (
        "EMERGENCY_STABILIZATION",
        "Recognize a severe COPD exacerbation with acute respiratory failure and urgently escalate care.",
        "SRC-MED-380-REC-01",
    ),
    "RDY-MED-02": (
        "NEXT_INVESTIGATION",
        "For intermittent palpitations, seek ECG documentation or symptom-rhythm correlation rather than diagnosing an arrhythmia from symptoms alone.",
        "SRC-MED-015-REC-01",
    ),
    "RDY-MED-03": (
        "DIAGNOSIS",
        "Distinguish a stable exertional angina pattern from new, worsening, rest, or unstable ischemic symptoms that require acute-coronary-syndrome assessment.",
        "SRC-MED-017-REC-01",
    ),
    "RDY-MED-05": (
        "DIAGNOSIS",
        "Assess a suspected adverse drug reaction with a complete temporal medication history and use the Canada Vigilance pathway when reporting is indicated.",
        "SRC-MED-030-REC-01",
    ),
    "RDY-MED-07": (
        "EMERGENCY_STABILIZATION",
        "Recognize mucosal, blistering, desquamative, or systemic findings after medication exposure as a severe cutaneous reaction requiring urgent assessment.",
        "SRC-MED-040-REC-01",
    ),
    "RDY-MED-08": (
        "INITIAL_MANAGEMENT",
        "Assess a purulent skin infection for severity and prioritize source-control assessment when an abscess is present.",
        "SRC-MED-037-REC-01",
    ),
    "RDY-MED-09": (
        "DIAGNOSIS",
        "Recognize a persistent pearly rolled-border lesion or a thickened scaly nonhealing lesion as suspicious for nonmelanoma skin cancer requiring timely assessment.",
        "SRC-MED-044-REC-01",
    ),
    "RDY-MED-10": (
        "ETHICAL_LEGAL_ACTION",
        "When elder abuse is suspected, assess immediate safety, interview the patient privately when feasible, document objectively, and follow the applicable reporting pathway.",
        "SRC-MED-438-REC-01",
    ),
}


# development_id, decision_type, learner_decision, normalized proposition,
# source_id, title, URL, exact locator
TARGETED_READY = [
    ("RDY-PED-01", "INITIAL_MANAGEMENT",
     "In a child with acute gastroenteritis and mild-to-moderate dehydration, use oral rehydration solution as initial rehydration when oral intake is safe.",
     "Oral rehydration solution is first-line rehydration for most children with mild-to-moderate dehydration from acute gastroenteritis when oral intake is safe.",
     "AUTH-RDY-CPS-DIARRHEA", "Dehydration and diarrhea in children: Prevention and treatment",
     "https://caringforkids.cps.ca/handouts/health-conditions-and-treatments/dehydration_and_diarrhea",
     "Treatment; oral rehydration solution"),
    ("RDY-PED-04", "EMERGENCY_STABILIZATION",
     "In a child with polyuria, polydipsia, and weight loss, immediately check glucose and ketones and urgently assess for diabetic ketoacidosis.",
     "Polyuria, polydipsia, and weight loss should trigger immediate glucose and ketone testing and urgent hospital assessment when pediatric diabetic ketoacidosis is possible.",
     "AUTH-RDY-CPS-DKA", "Diabetic ketoacidosis in children and youth",
     "https://cps.ca/uploads/infographics/DKA-Information_for_Healthcare_Providers-EN.pdf",
     "Signs and symptoms; immediate action"),
    ("RDY-PED-05", "EMERGENCY_STABILIZATION",
     "Treat fever in a child with sickle cell disease as an emergency requiring prompt blood culture and broad-spectrum antibiotics.",
     "A febrile child with sickle cell disease requires blood culture and prompt broad-spectrum antibiotics because functional asplenia creates a sepsis emergency.",
     "AUTH-RDY-CPS-SCD", "Acute complications in children with sickle cell disease: Prevention and management",
     "https://cps.ca/en/documents/position/acute-complications-with-sickle-cell",
     "Fever; recommendations"),
    ("RDY-PED-06", "NEXT_INVESTIGATION",
     "For a well-appearing febrile infant aged 0 to 28 days, obtain blood and urine testing with inflammatory markers and use age-specific lumbar-puncture and treatment guidance.",
     "Febrile infants aged 0 to 28 days require blood culture, urinalysis and urine culture, inflammatory markers, and age-specific consideration of lumbar puncture and empiric treatment.",
     "AUTH-RDY-CPS-FEBRILE-INFANT", "Management of well-appearing febrile young infants aged 90 days or younger",
     "https://cps.ca/en/documents/position/management-of-well-appearing-febrile-young-infants-aged-90-days",
     "Infants 0 to 28 days old; general principles"),
    ("RDY-PED-10", "MEDICATION_SELECTION",
     "Do not manage a child with confirmed mild asthma using as-needed short-acting beta-agonist alone; prescribe inhaled corticosteroid-containing therapy.",
     "Inhaled corticosteroid-containing therapy is first-line for mild pediatric asthma; short-acting beta-agonist monotherapy increases exacerbation risk.",
     "AUTH-RDY-CPS-MILD-ASTHMA", "The management of very mild and mild asthma in preschoolers, children, and adolescents",
     "https://cps.ca/en/documents/position/mild-asthma",
     "Pharmacological management; recommendations"),
    ("RDY-PED-12", "SCREENING_PREVENTION",
     "Provide caries-prevention counselling from the first tooth and establish a dental home by 12 months of age.",
     "Early-childhood-caries prevention begins with the first tooth and includes supervised fluoride exposure and establishment of a dental home by 12 months.",
     "AUTH-RDY-CPS-CARIES", "Early childhood caries",
     "https://cps.ca/en/documents/position/early-childhood-caries",
     "Recommendations; anticipatory guidance"),
    ("RDY-PED-13", "COMMUNICATION",
     "Offer adolescents private interview time, explain confidentiality and its safety or reporting limits, and assess decision-making capacity case by case.",
     "Adolescent care should include private time, a clear explanation of confidentiality limits, and case-specific assessment of capacity rather than an age-only rule.",
     "AUTH-RDY-CPS-ADOLESCENT-PRIVACY", "Privacy and confidentiality in adolescent health care",
     "https://cps.ca/en/documents/position/privacy-and-confidentiality-in-adolescent-health-care",
     "Recommendations; capacity and limits of confidentiality"),
    ("RDY-PED-14", "ETHICAL_LEGAL_ACTION",
     "When an injury is incompatible with a child's developmental stage or history, assess for additional injuries and report reasonable suspicion to child-protection authorities.",
     "Injury incompatible with development or history raises concern for maltreatment; clinicians must report reasonable suspicion to child-protection authorities.",
     "AUTH-RDY-CPS-MALTREATMENT", "The medical assessment of fractures in suspected child maltreatment",
     "https://cps.ca/en/documents/position/fractures-in-suspected-child-maltreatment",
     "Red flags; reporting duty"),

    ("RDY-OBGYN-01", "INITIAL_MANAGEMENT",
     "When pelvic inflammatory disease is clinically suspected, test for pregnancy and relevant infections and begin empiric broad-spectrum treatment without waiting for perfect diagnostic certainty.",
     "Early PID treatment is important; assessment includes pelvic examination, pregnancy testing and STI testing, and empiric therapy must cover likely polymicrobial causes.",
     "AUTH-RDY-PHAC-PID", "STI-associated syndromes guide: Pelvic inflammatory disease",
     "https://www.canada.ca/en/public-health/services/infectious-diseases/sexual-health-sexually-transmitted-infections/canadian-guidelines/sti-associated-syndromes/pelvic-inflammatory-disease.html",
     "Diagnostic testing; empiric treatment and management"),
    ("RDY-OBGYN-02", "NEXT_INVESTIGATION",
     "For pain or bleeding in early pregnancy, obtain transvaginal ultrasound and serum beta-hCG and continue follow-up until pregnancy location is established.",
     "Early-pregnancy pain or bleeding requires comprehensive assessment with transvaginal ultrasound and serum beta-hCG; pregnancy of unknown location requires serial follow-up.",
     "AUTH-RDY-OH-ECTOPIC", "Early Pregnancy Complications and Loss: Care for Adults in All Settings",
     "https://www.ontariohealth.ca/clinical/quality-standards/qs-details?cf=early-pregnancy-complications-loss",
     "Quality statements 1 and 3"),
    ("RDY-OBGYN-05", "MEDICATION_SELECTION",
     "For bothersome menopausal vasomotor symptoms, consider menopausal hormone therapy after individualized contraindication and risk-benefit assessment.",
     "Menopausal hormone therapy is first-line for vasomotor symptoms when individualized assessment finds no contraindication and benefits outweigh risks.",
     "AUTH-RDY-OH-MENOPAUSE", "Menopause: Care for People 40 Years of Age or Older",
     "https://sogc.org/common/Uploaded%20files/HUB%20Pages/menopause/qs-menopause-en.pdf",
     "Quality statement: treatment for vasomotor symptoms"),
    ("RDY-OBGYN-06", "INITIAL_MANAGEMENT",
     "Offer a vaginal pessary as a nonsurgical symptom-management option for pelvic organ prolapse when consistent with patient goals.",
     "A vaginal pessary is a legitimate nonsurgical option for symptom relief in pelvic organ prolapse and should be selected through patient-centred counselling.",
     "AUTH-RDY-SOGC-PESSARY", "Guideline No. 411: Vaginal Pessary Use",
     "https://pubmed.ncbi.nlm.nih.gov/33248302/",
     "Abstract; recommendations"),
    ("RDY-OBGYN-07", "NEXT_INVESTIGATION",
     "Evaluate an adnexal or pelvic mass with ultrasound-based characterization and malignancy-risk assessment to determine urgency and referral.",
     "Initial assessment of an adnexal mass uses clinical context and ultrasound characteristics to stratify malignancy risk and guide referral.",
     "AUTH-RDY-SOGC-ADNEXAL", "Guideline No. 403: Initial Investigation and Management of Adnexal Masses",
     "https://pubmed.ncbi.nlm.nih.gov/32736853/",
     "Abstract; objectives and recommendations"),
    ("RDY-OBGYN-10", "DIAGNOSIS",
     "Use ultrasound to diagnose and classify suspected placenta previa or low-lying placenta and arrange obstetric management.",
     "Placenta previa and low-lying placenta are diagnosed and classified by ultrasound to guide obstetric management.",
     "AUTH-RDY-SOGC-PREVIA", "Guideline No. 402: Diagnosis and Management of Placenta Previa",
     "https://pubmed.ncbi.nlm.nih.gov/32591150/",
     "Abstract; diagnosis and management"),
    ("RDY-OBGYN-11", "INITIAL_MANAGEMENT",
     "Give antenatal corticosteroids when preterm birth is expected within seven days between 24+0 and 34+6 weeks, absent a contraindication.",
     "Antenatal corticosteroids reduce neonatal morbidity and mortality when birth is expected within seven days at 24+0 to 34+6 weeks.",
     "AUTH-RDY-SOGC-ACS", "No. 364-Antenatal Corticosteroid Therapy for Improving Neonatal Outcomes",
     "https://pubmed.ncbi.nlm.nih.gov/30268316/",
     "Abstract; recommendations"),
    ("RDY-OBGYN-12", "EMERGENCY_STABILIZATION",
     "Treat severe hypertension in pregnancy as an obstetric urgency requiring prompt antihypertensive therapy and assess the indication for magnesium sulfate.",
     "Severe hypertension in pregnancy is an obstetric urgency requiring prompt treatment; magnesium sulfate is used for indicated seizure prophylaxis with clinical monitoring.",
     "AUTH-RDY-SOGC-HDP", "Guideline No. 426: Hypertensive Disorders of Pregnancy",
     "https://sogc.org/common/Uploaded%20files/ACSC/ACSC2024/gui426CPG2205E.pdf",
     "Recommendations 13 to 16; severe hypertension and magnesium sulphate"),

    ("RDY-SURG-03", "DIAGNOSIS",
     "Use thoracic point-of-care ultrasound, integrated with the clinical assessment, to evaluate suspected pneumothorax in an emergency presentation.",
     "Thoracic point-of-care ultrasound is a recognized emergency-physician application for identification of pneumothorax and must be interpreted with clinical context.",
     "AUTH-RDY-CAEP-POCUS", "Recommendations for the use of point-of-care ultrasound by emergency physicians in Canada",
     "https://www.caep.ca/position-statements/recommendations-for-the-use-of-point-of-care-ultrasound-%28pocus%29-by-emergency-physicians-in-canada",
     "Thoracic ultrasound; pneumothorax"),
    ("RDY-SURG-05", "INITIAL_MANAGEMENT",
     "Recognize resolved episodic biliary pain as biliary colic and refer appropriate symptomatic patients for elective laparoscopic cholecystectomy.",
     "Biliary pain that subsides without inflammatory complications is managed as biliary colic, with elective laparoscopic cholecystectomy considered for symptomatic disease.",
     "AUTH-RDY-CAGS-BILIARY", "Acute Care Surgery Handbook: Biliary Colic and Cholecystitis",
     "https://cags-accg.ca/wp-content/uploads/2019/07/ACS-Handbook-CPG-Ch-8-Biliary-Colic-and-Cholecystitis.pdf",
     "Biliary colic; management"),
    ("RDY-SURG-08", "INITIAL_MANAGEMENT",
     "In mechanical small bowel obstruction, identify peritonitis, strangulation, ischemia, perforation, or clinical deterioration as reasons for urgent operative assessment.",
     "Small bowel obstruction with peritonitis, strangulation, ischemia, perforation, or deterioration requires urgent surgical management rather than continued nonoperative care.",
     "AUTH-RDY-CAGS-SBO", "Acute Care Surgery Handbook: Small Bowel Obstructions",
     "https://cags-accg.ca/wp-content/uploads/2019/07/ACS-Handbook-CPG-Ch-12-Small-Bowel-Obstructions.pdf",
     "Diagnosis; indications for operative management"),
    ("RDY-SURG-09", "INITIAL_MANAGEMENT",
     "In acute diverticulitis, use clinical and imaging severity to distinguish uncomplicated disease from abscess, obstruction, fistula, or perforation requiring escalation.",
     "Complicated diverticulitis includes abscess, obstruction, fistula, or perforation and requires escalation beyond routine uncomplicated management.",
     "AUTH-RDY-CAGS-DIVERTICULITIS", "Acute Care Surgery Handbook: Diverticulitis",
     "https://cags-accg.ca/wp-content/uploads/2018/11/ACS-Handbook-CPG-Ch-17-Diverticulitis.pdf",
     "Classification; complicated diverticulitis"),
    ("RDY-SURG-12", "INTERPRETATION",
     "On abdominal radiography, recognize dilated small bowel with multiple air-fluid levels and paucity of colorectal gas as supporting small bowel obstruction.",
     "Dilated small bowel greater than about 3 cm with air-fluid levels and paucity of colorectal gas supports a radiographic diagnosis of small bowel obstruction.",
     "AUTH-RDY-CAGS-SBO", "Acute Care Surgery Handbook: Small Bowel Obstructions",
     "https://cags-accg.ca/wp-content/uploads/2019/07/ACS-Handbook-CPG-Ch-12-Small-Bowel-Obstructions.pdf",
     "Plain radiography findings"),
    ("RDY-SURG-13", "NEXT_INVESTIGATION",
     "Select urgent noncontrast head CT when acute head trauma raises concern for intracranial injury.",
     "Current Canadian imaging referral guidance supports CT-based assessment when acute head trauma raises concern for intracranial injury.",
     "AUTH-RDY-CAR-TRAUMA", "Canadian Association of Radiologists Trauma Referral Guidelines",
     "https://car.ca/wp-content/uploads/2025/03/CAR_Trauma_Referral_Guideline.pdf",
     "Head trauma summary recommendations"),
    ("RDY-SURG-14", "NEXT_INVESTIGATION",
     "When osteomyelitis remains clinically suspected after initial radiography, use MRI as the preferred advanced imaging test.",
     "MRI is the preferred advanced imaging modality for suspected osteomyelitis when diagnosis remains uncertain after initial assessment.",
     "AUTH-RDY-CPS-OSTEOARTICULAR", "Diagnosis and management of acute osteoarticular infections in children",
     "https://cps.ca/en/documents/position/acute-osteoarticular-infections-in-children",
     "Imaging; MRI"),
    ("RDY-SURG-15", "NEXT_INVESTIGATION",
     "Use MRI as the initial imaging modality for nontraumatic acute or progressive myelopathy rather than treating it as uncomplicated radiculopathy.",
     "Canadian referral guidance recommends MRI for nontraumatic acute-onset and chronic or progressive myelopathy.",
     "AUTH-RDY-CAR-SPINE", "Canadian Association of Radiologists Spine Referral Guidelines",
     "https://car.ca/wp-content/uploads/2025/03/CAR_Spine_Referral_Guideline_FINAL.pdf",
     "SP01 Myelopathy, recommendations 1 and 2"),

    ("RDY-PSY-01", "EMERGENCY_STABILIZATION",
     "Recognize postpartum psychosis as a psychiatric emergency and arrange urgent assessment to protect mother and infant.",
     "Postpartum psychosis is a psychiatric emergency associated with suicide and infanticide risk and usually requires urgent hospital assessment.",
     "AUTH-RDY-CAMH-POSTPARTUM", "Perinatal Mood and Anxiety Disorders: Diagnosis",
     "https://www.camh.ca/en/professionals/treating-conditions-and-disorders/perinatal-mood-and-anxiety-disorders/perinatal-mood---diagnosis",
     "Postpartum psychosis"),
    ("RDY-PSY-03", "DIAGNOSIS",
     "Recognize schizophrenia from persistent psychotic symptoms with functional decline and distinguish shorter psychotic disorders by course.",
     "Schizophrenia involves a persistent psychotic illness with functional impairment; duration and course help distinguish other psychotic disorders.",
     "AUTH-RDY-CAMH-PSYCHOSIS", "Psychosis",
     "https://www.camh.ca/en/health-info/mental-illness-and-addiction-index/psychosis",
     "Signs and symptoms; diagnosis"),
    ("RDY-PSY-04", "MEDICATION_SELECTION",
     "For panic disorder requiring medication, use an SSRI or SNRI as a first-line option and begin cautiously because early activation can worsen anxiety.",
     "SSRIs and SNRIs are effective medication options for panic disorder and should be started cautiously to limit initial activation.",
     "AUTH-RDY-CAMH-ANXIETY", "Anxiety Disorders: Pharmacotherapy",
     "https://www.camh.ca/en/professionals/treating-conditions-and-disorders/anxiety-disorders/anxiety---treatment/anxiety---pharmacotherapy",
     "Panic disorder; initiating pharmacotherapy"),
    ("RDY-PSY-05", "INITIAL_MANAGEMENT",
     "Offer cognitive behavioural therapy with exposure and response prevention as a first-line treatment for obsessive-compulsive disorder.",
     "Cognitive behavioural therapy using exposure to triggers without rituals, termed exposure and response prevention, is a first-line and highly effective OCD treatment.",
     "AUTH-RDY-CAMH-OCD", "OCD: Psychotherapy",
     "https://www.camh.ca/en/professionals/treating-conditions-and-disorders/ocd/ocd---treatment/ocd---psychotherapy",
     "Cognitive behavioural therapy; exposure and response prevention"),
    ("RDY-PSY-06", "INITIAL_MANAGEMENT",
     "After securing immediate safety in PTSD, offer trauma-focused psychotherapy as a first-line treatment.",
     "PTSD care begins with safety assessment; evidence-based trauma-focused psychotherapies are first-line treatments.",
     "AUTH-RDY-CAMH-PTSD", "PTSD: Treatment and Psychotherapy",
     "https://www.camh.ca/en/professionals/treating-conditions-and-disorders/ptsd/ptsd---treatment-and-psychotherapy",
     "Treatment options; psychotherapy"),
    ("RDY-PSY-07", "DIAGNOSIS",
     "Distinguish mild neurocognitive disorder from major disorder by preserved functional independence and distinguish delirium by acute fluctuating course.",
     "Mild neurocognitive disorder has objective cognitive decline without loss of functional independence; delirium has an acute, fluctuating course.",
     "AUTH-RDY-CAMH-DEMENTIA", "Dementia: Diagnosis",
     "https://www.camh.ca/en/professionals/treating-conditions-and-disorders/dementia/dementia---diagnosis",
     "Mild neurocognitive disorder; delirium"),
    ("RDY-PSY-09", "INITIAL_MANAGEMENT",
     "Use cognitive behavioural therapy for insomnia as first-line treatment for chronic insomnia.",
     "Cognitive behavioural therapy for insomnia is the standard first-line treatment for chronic insomnia.",
     "AUTH-RDY-CAMH-SLEEP", "Sleep Disorders: Treatment",
     "https://www.camh.ca/en/professionals/treating-conditions-and-disorders/sleep-disorders/sleep-disorders---treatment",
     "Insomnia; cognitive behavioural therapy"),
    ("RDY-PSY-15", "DIAGNOSIS",
     "Distinguish mania from hypomania by severity and functional disruption and screen for past elevated mood when assessing depression.",
     "Mania causes marked functional disruption and may include psychosis; hypomania is less severe, and past elevated mood should be sought during depression assessment.",
     "AUTH-RDY-CAMH-BIPOLAR", "Bipolar Disorder",
     "https://www.camh.ca/en/health-info/mental-illness-and-addiction-index/bipolar-disorder",
     "Manic phase; hypomania; diagnosis"),

    ("RDY-PHELO-02", "SCREENING_PREVENTION",
     "Classify risk-factor reduction before disease occurs as primary prevention, early detection as secondary prevention, and limitation of established disease effects as tertiary prevention.",
     "Primary prevention reduces causal risk before disease, secondary prevention detects and intervenes early, and tertiary prevention limits effects and recurrence of established disease.",
     "AUTH-RDY-PHAC-PREVENTION", "Implementing the Population Health Approach",
     "https://www.canada.ca/en/public-health/services/health-promotion/population-health/implementing-population-health-approach/implementing-population-health-approach.html",
     "Prevention"),
    ("RDY-PHELO-08", "ETHICAL_LEGAL_ACTION",
     "Assess capacity for the specific proposed decision by determining whether the patient understands relevant information and foreseeable consequences.",
     "Treatment capacity is time-, context-, and decision-specific and requires understanding relevant information and reasonably foreseeable consequences.",
     "AUTH-RDY-CMPA-CAPACITY", "Capacity assessments: Understanding the challenges for physicians",
     "https://www.cmpa-acpm.ca/en/advice-publications/browse-articles/2020/capacity-assessments-understanding-the-challenges-for-physicians",
     "Capacity for treatment; time and context specific"),
    ("RDY-PHELO-09", "ETHICAL_LEGAL_ACTION",
     "Before using clinical AI, assess privacy, equity, safety, accountability, transparency, and the adequacy of human oversight.",
     "Responsible health-AI adoption requires privacy and security, equity, safety and oversight, accountability, and transparent communication about AI's role.",
     "AUTH-RDY-HC-AI", "Pan-Canadian AI for Health Guiding Principles",
     "https://www.canada.ca/en/health-canada/corporate/transparency/health-agreements/pan-canadian-ai-guiding-principles.html",
     "Guiding principles 2 through 6"),
    ("RDY-PHELO-10", "INTERPRETATION",
     "Classify a dispute between individuals as civil law, prohibited conduct against public safety as criminal law, and review of government action as administrative law.",
     "Civil law resolves disputes between individuals, criminal law defines conduct prohibited by Parliament, and administrative law governs lawful and fair government action.",
     "AUTH-RDY-JUSTICE-LAW", "Definitions - Canada's Court System",
     "https://www.justice.gc.ca/eng/csj-sjc/ccs-ajc/06.html",
     "Definitions: administrative, civil, and criminal law"),
    ("RDY-PHELO-11", "INTERPRETATION",
     "Identify cohort, case-control, and cross-sectional studies from how participants are selected and whether exposure and outcomes are followed over time or measured at one point.",
     "Observational study design is identified from participant selection, exposure/outcome ascertainment, and follow-up structure rather than the clinical topic alone.",
     "AUTH-RDY-PHAC-STROBE", "How to integrate Intersectionality Theory in Health Equity analysis",
     "https://www.canada.ca/en/public-health/services/publications/science-research-data/how-integrate-intersectionality-theory-quantitative-health-equity-analysis.html",
     "STROBE checklist: study design and participants"),
    ("RDY-PHELO-12", "INTERPRETATION",
     "Interpret an incremental cost-effectiveness result using incremental costs and QALYs from the Canadian publicly funded health-care perspective.",
     "Canadian reference-case economic evaluation uses QALYs for health effects and reports incremental costs, QALYs, and the incremental cost-effectiveness ratio.",
     "AUTH-RDY-CDA-ECON", "Guidelines for the Economic Evaluation of Health Technologies: Canada, 4th Edition",
     "https://www.cda-amc.ca/sites/default/files/pdf/guidelines_for_the_economic_evaluation_of_health_technologies_canada_4th_ed.pdf",
     "Sections 10 and 15"),
    ("RDY-PHELO-13", "ETHICAL_LEGAL_ACTION",
     "Identify provincial or territorial authority for health-service delivery and professional regulation, while recognizing federal roles in national standards and regulated products.",
     "Provinces and territories deliver health services and regulate health professionals; the federal government administers national standards and regulates specified health products.",
     "AUTH-RDY-HC-SYSTEM", "About Canada's health care system",
     "https://www.canada.ca/en/health-canada/services/canada-health-care-system.html",
     "Canada's role in the health care system"),
    ("RDY-PHELO-14", "INTERPRETATION",
     "Interpret a wider 95% confidence interval around the same kind of estimate as indicating greater uncertainty and lower precision.",
     "A wider confidence interval reflects greater sampling uncertainty and lower precision than a narrower interval around the same kind of estimate.",
     "AUTH-RDY-STATCAN-CI", "Statistics 101: Confidence intervals",
     "https://www.statcan.gc.ca/en/wtc/data-literacy/catalogue/892000062022003",
     "Confidence-interval width, variability, and sample size"),
]


# One smallest clinically sufficient trigger feature per approved decision.
# feature_type and identity_type use the frozen registry ontologies.
FEATURE_TRIGGERS = {
    "RDY-MED-01": ("CLINICAL_JUDGEMENT", "SEVERITY", "a COPD exacerbation is severe and complicated by acute respiratory failure"),
    "RDY-MED-02": ("SYSTEM_CONSTRAINT", "CONTEXT", "intermittent palpitations have not yet been correlated with an ECG rhythm"),
    "RDY-MED-03": ("SYMPTOM", "PRESENTATION", "ischemic chest symptoms are new, worsening, occurring at rest, or otherwise unstable"),
    "RDY-MED-05": ("HISTORY", "PRESENTATION", "a new clinical problem has a plausible temporal relationship to a medication exposure"),
    "RDY-MED-07": ("EXAMINATION_FINDING", "FINDING", "mucosal injury, blistering, desquamation, or systemic illness follows medication exposure"),
    "RDY-MED-08": ("EXAMINATION_FINDING", "FINDING", "a purulent skin collection consistent with an abscess is present"),
    "RDY-MED-09": ("EXAMINATION_FINDING", "FINDING", "a persistent pearly rolled-border or thickened scaly nonhealing skin lesion is present"),
    "RDY-MED-10": ("CLINICAL_JUDGEMENT", "PRESENTATION", "the history or findings raise a reasonable concern for elder abuse"),

    "RDY-PED-01": ("CLINICAL_JUDGEMENT", "SEVERITY", "a child with acute gastroenteritis has mild-to-moderate dehydration and can take oral fluids safely"),
    "RDY-PED-04": ("SYMPTOM", "PRESENTATION", "a child has polyuria, polydipsia, and weight loss suggesting new diabetes"),
    "RDY-PED-05": ("VITAL_SIGN", "PRESENTATION", "a child with sickle cell disease has fever"),
    "RDY-PED-06": ("AGE", "CONTEXT", "a febrile infant is 28 days old or younger"),
    "RDY-PED-10": ("CLINICAL_JUDGEMENT", "DIAGNOSIS", "mild pediatric asthma is confirmed and requires controller planning"),
    "RDY-PED-12": ("AGE", "CONTEXT", "an infant's first tooth has erupted and preventive dental guidance is due"),
    "RDY-PED-13": ("DEMOGRAPHIC", "CONTEXT", "the patient is an adolescent receiving a confidential clinical interview"),
    "RDY-PED-14": ("CLINICAL_JUDGEMENT", "PRESENTATION", "a child's injury is incompatible with developmental stage or the stated mechanism"),

    "RDY-OBGYN-01": ("EXAMINATION_FINDING", "PRESENTATION", "pelvic findings create clinical suspicion for pelvic inflammatory disease"),
    "RDY-OBGYN-02": ("SYMPTOM", "PRESENTATION", "pain or bleeding is present in an early pregnancy whose location is not established"),
    "RDY-OBGYN-05": ("SYMPTOM", "PRESENTATION", "bothersome menopausal vasomotor symptoms are present"),
    "RDY-OBGYN-06": ("PATIENT_PREFERENCE", "CONTEXT", "a patient with symptomatic pelvic organ prolapse prefers a nonsurgical option"),
    "RDY-OBGYN-07": ("INVESTIGATION_RESULT", "TEST_RESULT", "an adnexal mass has ultrasound features requiring malignancy-risk stratification"),
    "RDY-OBGYN-10": ("INVESTIGATION_RESULT", "TEST_RESULT", "ultrasound shows placenta previa or a low-lying placenta"),
    "RDY-OBGYN-11": ("CLINICAL_JUDGEMENT", "INDICATION", "preterm birth is expected within seven days at 24+0 to 34+6 weeks"),
    "RDY-OBGYN-12": ("VITAL_SIGN", "SEVERITY", "severe hypertension is present during pregnancy"),

    "RDY-SURG-03": ("CLINICAL_JUDGEMENT", "PRESENTATION", "the emergency presentation raises clinical suspicion for pneumothorax"),
    "RDY-SURG-05": ("TIME_COURSE", "PRESENTATION", "episodic biliary pain has resolved without evidence of an inflammatory complication"),
    "RDY-SURG-08": ("EXAMINATION_FINDING", "SEVERITY", "small bowel obstruction is accompanied by peritonitis, ischemia, perforation, or clinical deterioration"),
    "RDY-SURG-09": ("INVESTIGATION_RESULT", "SEVERITY", "diverticulitis is complicated by abscess, obstruction, fistula, or perforation"),
    "RDY-SURG-12": ("INVESTIGATION_RESULT", "TEST_RESULT", "abdominal radiography shows dilated small bowel, air-fluid levels, and paucity of colorectal gas"),
    "RDY-SURG-13": ("HISTORY", "INDICATION", "acute head trauma raises concern for intracranial injury"),
    "RDY-SURG-14": ("CLINICAL_JUDGEMENT", "INDICATION", "osteomyelitis remains clinically suspected after initial assessment"),
    "RDY-SURG-15": ("EXAMINATION_FINDING", "PRESENTATION", "nontraumatic acute or progressive myelopathic findings are present"),

    "RDY-PSY-01": ("SYMPTOM", "PRESENTATION", "psychotic symptoms develop in the early postpartum period"),
    "RDY-PSY-03": ("LONGITUDINAL_COURSE", "DIAGNOSIS", "persistent psychotic symptoms are accompanied by functional decline"),
    "RDY-PSY-04": ("CLINICAL_JUDGEMENT", "INDICATION", "panic disorder requires a medication treatment option"),
    "RDY-PSY-05": ("CLINICAL_JUDGEMENT", "DIAGNOSIS", "obsessive-compulsive disorder is established and treatment is being selected"),
    "RDY-PSY-06": ("CLINICAL_JUDGEMENT", "INDICATION", "post-traumatic stress disorder is established and immediate safety has been assessed"),
    "RDY-PSY-07": ("LONGITUDINAL_COURSE", "PRESENTATION", "cognitive decline is present but functional independence is preserved"),
    "RDY-PSY-09": ("LONGITUDINAL_COURSE", "DIAGNOSIS", "chronic insomnia is established"),
    "RDY-PSY-15": ("LONGITUDINAL_COURSE", "PRESENTATION", "a past period of elevated mood caused marked functional disruption"),

    "RDY-PHELO-02": ("PROGRAMME_OBJECTIVE", "PROPOSITION", "an intervention targets risk before disease, early detection, or limitation of established disease effects"),
    "RDY-PHELO-08": ("CLINICAL_JUDGEMENT", "PROPOSITION", "capacity is being assessed for a specific proposed treatment decision"),
    "RDY-PHELO-09": ("PROGRAMME_DOCUMENT", "PROPOSITION", "a proposed clinical AI use requires privacy, equity, safety, accountability, and transparency review"),
    "RDY-PHELO-10": ("PROGRAMME_DOCUMENT", "PROPOSITION", "a legal scenario describes a private dispute, prohibited public conduct, or review of government action"),
    "RDY-PHELO-11": ("STUDY_DESIGN", "PROPOSITION", "an observational study describes participant selection, exposure ascertainment, outcome ascertainment, and follow-up"),
    "RDY-PHELO-12": ("STUDY_RESULT", "TEST_RESULT", "an economic evaluation reports incremental costs and incremental QALYs"),
    "RDY-PHELO-13": ("PROGRAMME_DOCUMENT", "PROPOSITION", "a healthcare legal question concerns service delivery, professional regulation, national standards, or regulated products"),
    "RDY-PHELO-14": ("STUDY_RESULT", "TEST_RESULT", "a 95 percent confidence interval is wide relative to the estimate's scale"),
}


# Safe identity-preserving reuse from V5, in addition to the trigger above.
EXISTING_FEATURE_BINDINGS = [
    ("RDY-OBGYN-01", "SF-GS76-CERVICAL-MOTION-OR-ADNEXAL-TENDERNESS"),
    ("RDY-OBGYN-01", "SF-GS76-FEMALE-REPRODUCTIVE-AGE"),
    ("RDY-OBGYN-02", "SF-GS76-FEMALE-REPRODUCTIVE-AGE"),
    ("RDY-OBGYN-02", "SF-GS76-PREGNANT"),
    ("RDY-OBGYN-11", "SF-GS76-PREGNANT"),
    ("RDY-OBGYN-12", "SF-GS76-PREGNANT"),
    ("RDY-SURG-09", "SF-GS76-PERFORATION-WITH-PERITONITIS"),
    ("RDY-PHELO-11", "SF-ONB2-SAMPLING-FRAME"),
    ("RDY-PSY-15", "SF-PS12-PAST-HYPOMANIC-PERIOD"),
]
